# Tugas Untuk Get data

- Untuk membuat pipelines, perlu menggunakan hosting melalui Cloud cluster secara online di https://www.cloudclusters.io/
- Kemudian login untuk meneruskan pada setiap tools yang dibutuhkan
- Lakukan "order now" pada tools yang dipilih, lalu akan diteruskan untuk me-manage nama database dan user pada setiap tools
- Selanjutnya membuat database sesuai dengan perintah yaitu :
  - postgresql local dengan data sepal length 
  - postgresql elephant dengan data sepal width 
  - mysql local dengan petal length 
  - sql server local dengan petal width dan class 

- Setelah data dari beberapa sumber telah dibuat, barulah membuat 'new pipeline' pada https://www.orchest.io/
- Environment disesuaikan dengan menggunakan bahasa pemrograman python dengan memasukan perintah


```
          pip install pandas scikit-learn matplotlib
          pip install psycopg2-binary
          pip install pymssql
          pip install mysql-connector-python
```

- Tahap setelahnya adalah membuat file python berdasarkan data yang diambil dari masing-masing tools sebagai berikut

### Ambil Data melalui Postgresql

In [ ]:
import psycopg2
import pandas as pd
import orchest
# Connection parameters, yours will be different
param_dic = {
    "host"      : "postgresql-152554-0.cloudclusters.net",
    "database"  : "prosaindata",
    "port"  : "15871",
    "user"      : "adila",
    "password"  : "adi1423"
}
def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    print("Connection successful")
    return conn

def postgresql_to_dataframe(conn, select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = conn.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Naturally we get a list of tupples
    tupples = cursor.fetchall()
    cursor.close()
    
    # We just need to turn it into a pandas dataframe
    df = pd.DataFrame(tupples, columns=column_names)
    return df

# Connect to the database
conn = connect(param_dic)

column_names = ["id","sepallength"]

df = postgresql_to_dataframe(conn, "select * from sepallength", column_names)
print(df)

### Ambil Data melalui Mysql

In [ ]:
import mysql.connector
import pandas as pd
import orchest
db = mysql.connector.connect(
  host="mysql-115437-0.cloudclusters.net",
  port="10294",
  user="admin",
  passwd="69K2X1Ca",
  database  = "prosaindata"
)

def postgresql_to_dataframe(select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = db.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Naturally we get a list of tupples
    tupples = cursor.fetchall()
    cursor.close()
    
    # We just need to turn it into a pandas dataframe
    df = pd.DataFrame(tupples, columns=column_names)
    return df

# Connect to the database
column_names = ["id","petallength"]
df = postgresql_to_dataframe("select * from petallength", column_names)
print(df)

### Ambil Data melalui SQLserver

In [ ]:
import pymssql
import pandas as pd
import orchest
connection = pymssql.connect(
    server='mssql-112155-0.cloudclusters.net',
    port = '19452',
    user='adila123',
    password='adila123',
    database='prosaindata'
)

def postgresql_to_dataframe(select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = connection.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Naturally we get a list of tupples
    tupples = cursor.fetchall()
    cursor.close()
    
    # We just need to turn it into a pandas dataframe
    df = pd.DataFrame(tupples, columns=column_names)
    return df

# Connect to the database
column_names = ["id","petalwidth","class"]
df = postgresql_to_dataframe("select * from petalwidth_class", column_names)
print(df)

### Ambil Data melalui Elephansql

In [ ]:
import psycopg2
import pandas as pd
# Connection parameters, yours will be different
param_dic = {
    "host"      : "floppy.db.elephantsql.com",
    "database"  : "zwflsmfo",
    "user"      : "zwflsmfo",
    "password"  : "7IE_NCIgyZ11GlH04eSIJBqnAnRfUHol"
}
def connect(params_dic):
    """ Connect to the PostgreSQL database server """
    conn = None
    try:
        # connect to the PostgreSQL server
        print('Connecting to the PostgreSQL database...')
        conn = psycopg2.connect(**params_dic)
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        sys.exit(1) 
    print("Connection successful")
    return conn

def postgresql_to_dataframe(conn, select_query, column_names):
    """
    Tranform a SELECT query into a pandas dataframe
    """
    cursor = conn.cursor()
    try:
        cursor.execute(select_query)
    except (Exception, psycopg2.DatabaseError) as error:
        print("Error: %s" % error)
        cursor.close()
        return 1
    
    # Naturally we get a list of tupples
    tupples = cursor.fetchall()
    cursor.close()
    
    # We just need to turn it into a pandas dataframe
    df = pd.DataFrame(tupples, columns=column_names)
    return df

# Connect to the database
conn = connect(param_dic)

column_names = ["sepal_I","sepal_w","petal_I","petal_W","class"]

df = postgresql_to_dataframe(conn, "select * from iris", column_names)

## Semua data akan menggunakan output berikut

In [ ]:
# Output the housing data so the next steps can retrieve it.
print("Outputting converted housing data...")
orchest.output(df, name="datapetalwidth-class")
print("Success!")